      - name: Mypy
        run: |
          . .venv/bin/activate
          python -m mypy src scripts plugins

      - name: Install Playwright browser
        run: |
          . .venv/bin/activate
          python -m playwright install --with-deps --only-shell

      - name: Pytest
        run: |
          . .venv/bin/activate
          pytest

      - name: Detect changes in scripts/
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            scripts:
              - 'scripts/**'
